2 Laboras/Models/Asistentas.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace _2_Laboras.Models
{
    public class Asistentas
    {
        public string Vardas { get; set; }
        public string Pavarde { get; set; }
        public string Tautybe { get; set; }
        public int id { get; set; }
        public int fk_treneris { get; set; }
    }
}

2 Laboras/Controllers/AsistentasController.cs
using System;
using System.Collections.Generic;
using System.Web.Mvc;
using _2_Laboras.Repos;
using _2_Laboras.ViewModels;

namespace _2_Laboras.Controllers
{
    public class AsistentasController : Controller
    {
        AsistentasRepository asistentasRepository = new AsistentasRepository();
        TrenerisRepository trenerisRepository = new TrenerisRepository();
        public ActionResult Index()
        {
            return View(asistentasRepository.getAsistentai());
        }

        public ActionResult Create()
        {
            AsistentasEditViewModel asistentas = new AsistentasEditViewModel();
            PopulateSelections(asistentas);
            return View(asistentas);
        }

        [HttpPost]
        public ActionResult Create(AsistentasEditViewModel collection)
        {
            try
            {
                if (ModelState.IsValid)
                    asistentasRepository.addAsistentas(collection);

                return RedirectToAction("Index");
            }
            catch
            {
                PopulateSelections(collection);
                return View(collection);
            }
        }

        public ActionResult Edit(int id)
        {
            AsistentasEditViewModel asistentas = asistentasRepository.getAsistentas(id);
            PopulateSelections(asistentas);
            return View(asistentas);
        }

        [HttpPost]
        public ActionResult Edit(int id, AsistentasEditViewModel collection)
        {
            try
            {
                if (ModelState.IsValid)
                    asistentasRepository.updateAsistentas(collection);

                return RedirectToAction("Index");
            }

            catch
            {
                PopulateSelections(collection);
                return View(collection);
            }
        }

        public ActionResult Delete(int id)
        {
            AsistentasEditViewModel asistentas = asistentasRepository.getAsistentas(id);
            return View(asistentas);
        }

        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                asistentasRepository.deleteAsistentas(id);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        public void PopulateSelections(AsistentasEditViewModel asistentas)
        {
            var treneriai = trenerisRepository.getTreneris();
            List<SelectListItem> selectListItems = new List<SelectListItem>();

            foreach(var item in treneriai)
            {
                selectListItems.Add(new SelectListItem() { Value = Convert.ToString(item.id), Text = item.Vardas + " " + item.Pavarde });
            }

            asistentas.TreneriaiList = selectListItems;
        }
    }
}

2 Laboras/Views/Asistentas/Create.cshtml
@model _2_Laboras.ViewModels.AsistentasEditViewModel

@{
    ViewBag.Title = "Naujas asistentas";
}

<h2>Naujas asistentas</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Asistento informacija</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Vardas, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Vardas, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Vardas, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Pavarde, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Pavarde, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Pavarde, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Tautybe, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Tautybe, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Tautybe, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.fk_treneris, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.fk_treneris, Model.TreneriaiList,"-----------", new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.fk_treneris, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Išsaugoti" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Atgal į sąrašą »", "Index", "Asistentas", new { @class="btn btn-default"})
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

2 Laboras/Views/Asistentas/Delete.cshtml
@model _2_Laboras.ViewModels.AsistentasEditViewModel


@{
    ViewBag.Title = "Asistento šalinimas";
}

<h2>Asistento šalinimas</h2>

<h3>Ar tikrai norite pašalinti šį asistentą?</h3>
<div>
    <h4>Asistentas</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Vardas)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Vardas)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Pavarde)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Pavarde)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Tautybe)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Tautybe)
        </dd>


    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Šalinti" class="btn btn-danger" />     
            @Html.ActionLink("Atgal į sąrašą >>", "Index", "Asistentas", new { @class="btn btn-default"})
        </div>
    }
</div>

2 Laboras/Views/Asistentas/Edit.cshtml
@model _2_Laboras.ViewModels.AsistentasEditViewModel

@{
    ViewBag.Title = "Asistento redagavimas";
}

<h2>Asistento redagavimas</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <fieldset>
        <legend>Asistento informacija</legend>

        <div class="form-horizontal">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.id)

            <div class="form-group">
                @Html.LabelFor(model => model.Vardas, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Vardas, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Vardas, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Pavarde, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Pavarde, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Pavarde, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Tautybe, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Tautybe, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Tautybe, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.fk_treneris, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownListFor(model => model.fk_treneris, Model.TreneriaiList, "--------------", new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.fk_treneris, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Išsaugoti" class="btn btn-success" />
                </div>
            </div>
        </div>
    </fieldset>
}

<div>
    @Html.ActionLink("Atgal į sarašą »", "Index", "Asistentas", new { @class = "btn btn-default" })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

2 Laboras/Views/Asistentas/Index.cshtml
@model IEnumerable<_2_Laboras.ViewModels.AsistenasViewModel>

@{
    ViewBag.Title = "Asistentai";
}

    <h2>Asistentai</h2>

<p>
    @Html.ActionLink("Naujas asistentas", "Create", "Asistentas", new { @class="btn btn-success"})
</p>
<table class="table">
    <thead>
        <tr style="background-color: lightblue; ">
            <th>
                @Html.DisplayNameFor(model => model.Vardas)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Pavarde)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Tautybe)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Treneris)
            </th>
            <th style="width: 18%"></th>
        </tr>
    </thead>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Vardas)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Pavarde)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Tautybe)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Treneris)
                </td>
                <td>
                    @Html.ActionLink("Redaguoti", "Edit", new { id = item.id }, new { @class = "btn btn-primary action" })
                    @Html.ActionLink("Šalinti", "Delete", new { id = item.id }, new { @class = "btn btn-danger action" })
                </td>
            </tr>
        }

</table>