2 Laboras/Controllers/ArenaController.cs
using System;
using System.Web.Mvc;
using System.Collections.Generic;
using _2_Laboras.Repos;
using _2_Laboras.ViewModels;

namespace _2_Laboras.Controllers
{
    public class ArenaController: Controller
    {
        ArenaRepository arenaRepository = new ArenaRepository();

        // GET: Arenos
        public ActionResult Index()
        {
            // Grazinamas arenų sąrašas
            return View(arenaRepository.getArena());
        }

        // GET: Arena/Create
        public ActionResult Create()
        {
            ArenaEditViewModel arena = new ArenaEditViewModel();
            PopulateSelections(arena);
            return View(arena);
        }

        // POST: Arena/Create
        [HttpPost]
        public ActionResult Create(ArenaEditViewModel collection)
        {
            try
            {       
                bool exist = arenaRepository.findDublicates(collection.Pavadinimas);
                if (exist)
                {
                    ViewBag.klaida = "Arena su tokiu pavadinimu jau egzistuoja";
                    PopulateSelections(collection);
                    return View(collection);
                }

                if (ModelState.IsValid)
                {
                    arenaRepository.addArena(collection);
                }

                return RedirectToAction("Index");
            }
            catch
            {
                PopulateSelections(collection);
                return View(collection);
            }
        }
        
        // GET: Arena/Edit
        public ActionResult Edit(int id)
        {
            ArenaEditViewModel arena = arenaRepository.getArena(id);
            PopulateSelections(arena);
            return View(arena);
        }

        // GET: Arena/Edit
        [HttpPost]
        public ActionResult Edit(ArenaEditViewModel collection)
        {
            try
            {
                bool exist = arenaRepository.findDbulicatesForEdit(collection.Pavadinimas,collection.id) ;
                if (exist)
                {
                    ViewBag.klaida = "Arena su tokiu pavadinimu jau egzistuoja";
                    PopulateSelections(collection);
                    return View(collection);
                }

                if (ModelState.IsValid)
                {
                    arenaRepository.updateArena(collection);
                }

                return RedirectToAction("Index");
            }

            catch
            {
                PopulateSelections(collection);
                return View(collection);
            }
        }

        // GET: Arena/Delete

        public ActionResult Delete(int id)
        {
            ArenaEditViewModel arena = arenaRepository.getArena(id);
            return View(arena);
        }

        // POST: Arena/Delete
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
 
            try
            {
                arenaRepository.deleteArena(id);
                return RedirectToAction("Index");
            }

            catch
            {
                return View();
            }
        }

        public void PopulateSelections(ArenaEditViewModel arenaEditViewModel)
        {
            var miestai = arenaRepository.getMiestai();
            List<SelectListItem> selectListMiestai = new List<SelectListItem>();

            foreach (var item in miestai)
            {
                selectListMiestai.Add(new SelectListItem() { Value = Convert.ToString(item.id), Text = item.Pavadinimas });
            }

            arenaEditViewModel.MiestaiList = selectListMiestai;

        }


    }
}

2 Laboras/Controllers/TrenerisController.cs
using System;
using System.Web.Mvc;
using _2_Laboras.Models;
using _2_Laboras.Repos;
using System.Collections.Generic;

namespace _2_Laboras.Controllers
{
    public class TrenerisController: Controller
    {
        TrenerisRepository trenerisRepository = new TrenerisRepository();

        public ActionResult Index()
        {
            return View(trenerisRepository.getTreneris());
        }

        public ActionResult Create()
        {
            Treneris treneris = new Treneris();
            return View(treneris);
        }

        [HttpPost]
        public ActionResult Create(Treneris treneris)
        {
            try
            {
                if (ModelState.IsValid)
                    trenerisRepository.addTreneris(treneris);

                return RedirectToAction("Index");
            }
            catch
            {
                return View(treneris);
            }
        }

        public ActionResult Edit(int id)
        {
            return View(trenerisRepository.getTreneris(id));
        }

        [HttpPost]
        public ActionResult Edit(Treneris treneris)
        {
            try
            {
                if (ModelState.IsValid)
                    trenerisRepository.updateTreneris(treneris);

                return RedirectToAction("Index");
            }
            catch
            {
                return View(treneris);
            }
        }

        public ActionResult Delete(int id)
        {
            return View(trenerisRepository.getTreneris(id));
        }

        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                Treneris treneris = trenerisRepository.getTreneris(id);
                List<Asistentas> asistentas = trenerisRepository.getAsistentai(id);

                if(asistentas.Count > 0)
                {
                    ViewBag.klaida = "Negalima ištrinti trenerio, nes jis turi asistentus";
                    return View(treneris);
                }
                else
                {
                    trenerisRepository.deleteTreneris(id);
                }
                
                return RedirectToAction("Index");
            }

            catch
            {
                return View();
            }
        }

    }

}

2 Laboras/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/themes/base/jquery-ui.min.css" rel="stylesheet" />
    <link href="~/Content/jquery.datetimepicker.css" rel="stylesheet" />
    <link href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css" rel="stylesheet" />
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Krepšinio IS", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Komandos", "Index", "Krepsinio_komanda")</li>
                    <li>@Html.ActionLink("Treneriai", "Index", "Treneris")</li>
                    <li>@Html.ActionLink("Asistentai", "Index", "Asistentas")</li>
                    <li>@Html.ActionLink("Arenos", "Index", "Arena")</li>
                    <li>@Html.ActionLink("Krepšinio lygos", "Index", "Krepsinio_lyga")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Patrikas Voicechovski</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    <script src="~/Scripts/jquery-ui-1.12.1.min.js"></script>
    <script src="~/Scripts/jquery.datetimepicker.js"></script>
    <script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
    @RenderSection("scripts", required: false)
</body>
</html>