2 Laboras/Models/Krepsinio_komanda.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
namespace _2_Laboras.Models
{
    public class Krepsinio_komanda
    {
        [DisplayName("ID")]
        [Required]
        public int id { get; set; }

        [DisplayName("Pavadinimas")]
        [Required]
        public string Pavadinimas { get; set; }

        [DisplayName("Miestas")]
        [Required]
        public string Miestas { get; set; }

        [DisplayName("Treneris")]
        [Required]
        public string Treneris { get; set; }

        [DisplayName("Biudžetas")]
        [Required]
        public int Biudzetas { get; set; }

        [DisplayName("Arena")]
        [Required]
        public string Arena { get; set; }

        [DisplayName("Lygų licenzijos")]
        [Required]
        public string Lygu_licenzija { get; set; }

        [DisplayName("Laimėjimai")]
        [Required]
        public string Laimejimai { get; set; }
       
        public virtual IEnumerable<Darbuotojas> Darbuotojai { get; set; }
    }
}

2 Laboras/ViewModels/KrepsinioKomandaViewModel.cs
using System;
using System.ComponentModel;


namespace _2_Laboras.ViewModels
{
    public class KrepsinioKomandaViewModel
    {
        [DisplayName("Komandos pavadinimas")]
        public string Pavadinimas { get; set; }
        [DisplayName("Miestas")]
        public string Miestas { get; set; }
        [DisplayName("Treneris")]
        public string Treneris { get; set; }
        [DisplayName("Biudžetas")]
        public int Biudzetas { get; set; }

    }
}

2 Laboras/Controllers/Krepsinio_komandaController.cs
using System;
using System.Web.Mvc;
using _2_Laboras.ViewModels;
using _2_Laboras.Repos;
using System.Collections.Generic;
using System.Linq;

namespace _2_Laboras.Controllers
{
    public class Krepsinio_komandaController: Controller
    {
        Krepsinio_komandaRepository komandaRepository = new Krepsinio_komandaRepository();
        DarbuotojasRepository darbuotojasRepository = new DarbuotojasRepository();
        public ActionResult Index()
        {
            return View(komandaRepository.getKrepsinio_Komanda());
        }

        public ActionResult Create()
        {
            KrepsinioKomandaEditViewModel krepsinioKomanda = new KrepsinioKomandaEditViewModel();
            return View(krepsinioKomanda);
        }

        [HttpPost]
        public ActionResult Create(KrepsinioKomandaEditViewModel komanda)
        {
            try
            {
                bool exist = komandaRepository.findDublicates(komanda.KrepsinioKomanda.Pavadinimas);
                if (exist)
                {
                    ViewBag.klaida = "Komanda su tokiu pavadinimu jau egzistuoja";
                    return View(komanda);
                }


                int komanda_id = komandaRepository.addKrepsinio_Komanda(komanda.KrepsinioKomanda);
                if (komanda_id < 0)
                {
                    ViewBag.failed = "Nepavyko pridėti komandos";
                    return View(komanda);
                }

                if(komanda.Darbuotojai != null)
                {
                    foreach(var darbuotojas in komanda.Darbuotojai)
                    {
                        darbuotojas.fk_krepsinioKomanda = komanda_id;
                        darbuotojasRepository.addDarbuotojas(darbuotojas);
                    }
                }

                return RedirectToAction("Index");
            }

            catch
            {
                ViewBag.klaida = "Visi darbuotojo duomenys yra reikalingi";
                return View(komanda);
            }
        }

        public ActionResult Edit(int id)
        {
            KrepsinioKomandaEditViewModel krepsinioKomandaEditViewModel = new KrepsinioKomandaEditViewModel();
            krepsinioKomandaEditViewModel.KrepsinioKomanda = komandaRepository.getKrepsinio_Komanda(id);
            krepsinioKomandaEditViewModel.Darbuotojai = darbuotojasRepository.getDarbuotojai(id);
            return View(krepsinioKomandaEditViewModel);
        }

        [HttpPost]
        public ActionResult Edit(int id, KrepsinioKomandaEditViewModel komanda)
        {
            try
            {
                bool exist = komandaRepository.findDbulicatesForEdit(komanda.KrepsinioKomanda.Pavadinimas, id);
                if (exist)
                {
                    ViewBag.klaida = "Komanda su tokiu pavadinimu jau egzistuoja";
                    return View(komanda);
                }

                komandaRepository.updateKrepsinio_Komanda(id,komanda.KrepsinioKomanda);

                if(komanda.Darbuotojai != null)
                {
                    darbuotojasRepository.deleteDarbuotojas(id);
                    foreach (var darbuotojas in komanda.Darbuotojai)
                    {
                        darbuotojas.fk_krepsinioKomanda = id;
                        darbuotojasRepository.addDarbuotojas(darbuotojas);
                    }
                } 

                return RedirectToAction("Index");
            }
            catch
            {
                ViewBag.klaida = "Visi darbuotojo duomenys yra reikalingi";
                return View(komanda);
            }
        }

        public ActionResult Delete(int id)
        {
            KrepsinioKomandaEditViewModel krepsinioKomandaEditViewModel = new KrepsinioKomandaEditViewModel();
            krepsinioKomandaEditViewModel.KrepsinioKomanda = komandaRepository.getKrepsinio_Komanda(id);
            krepsinioKomandaEditViewModel.Darbuotojai = darbuotojasRepository.getDarbuotojai(id);
            return View(krepsinioKomandaEditViewModel);
        }

        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                KrepsinioKomandaEditViewModel krepsinioKomandaEditViewModel = new KrepsinioKomandaEditViewModel();
                krepsinioKomandaEditViewModel.KrepsinioKomanda = komandaRepository.getKrepsinio_Komanda(id);
                krepsinioKomandaEditViewModel.Darbuotojai = darbuotojasRepository.getDarbuotojai(id);
                darbuotojasRepository.deleteDarbuotojas(id);
                komandaRepository.deleteKrepsinio_Komanda(id);
                return RedirectToAction("Index");
            }

            catch(Exception e)
            {
                ViewBag.klaida = e;
                return View();
            }
        }

    }
}

2 Laboras/Views/Krepsinio_komanda/Create.cshtml
@model _2_Laboras.ViewModels.KrepsinioKomandaEditViewModel

@{
    ViewBag.Title = "Nauja komanda";
}

<h2>Nauja komanda</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Krepšinio komanda</h4>
    <hr />
      <fieldset>
          <legend>Krepšinio komandos informacija</legend>
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.KrepsinioKomanda.Pavadinimas, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.KrepsinioKomanda.Pavadinimas, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.KrepsinioKomanda.Pavadinimas, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.KrepsinioKomanda.Miestas, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.KrepsinioKomanda.Miestas, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.KrepsinioKomanda.Miestas, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.KrepsinioKomanda.Treneris, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.KrepsinioKomanda.Treneris, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.KrepsinioKomanda.Treneris, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.KrepsinioKomanda.Biudzetas, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.KrepsinioKomanda.Biudzetas, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.KrepsinioKomanda.Biudzetas, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.KrepsinioKomanda.Arena, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.KrepsinioKomanda.Arena, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.KrepsinioKomanda.Arena, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.KrepsinioKomanda.Lygu_licenzija, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.KrepsinioKomanda.Lygu_licenzija, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.KrepsinioKomanda.Lygu_licenzija, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.KrepsinioKomanda.Laimejimai, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.KrepsinioKomanda.Laimejimai, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.KrepsinioKomanda.Laimejimai, "", new { @class = "text-danger" })
            </div>
        </div>
        </fieldset>

      <fieldset>
          <legend>Komandos darbuotojai</legend>
          <table class="table-responsive" id="darbuotojai_tbl">
              <thead id="header" style="visibility: hidden">
                  <tr>
                      <th>Vardas</th>
                      <th>Pavardė</th>
                      <th>Einamos pareigos</th>
                  </tr>
              </thead>
          </table>
          <input type="hidden" disabled value="0" id="hCount" />
          <button id="prd" type="button" class="btn btn-info" onclick="prideti($('#hCount').val());" style="margin-top: 10px">Pridėti</button>
          @if (ViewBag.klaida != null)
          {
              <h5 style="color:red">@ViewBag.klaida</h5>
          }
          else
          {
            <input type="submit" value="Išsaugoti" class="btn btn-success" style="margin-top: 10px" />
          }
      </fieldset>

        <div class="form-group" >
            <div class="col-md-offset-2 col-md-10">
                
            </div>
        </div>
</div>
}

<div>
    @Html.ActionLink("Atgal į sąrašą »", "Index", "Krepsinio_komanda",  new { @class="btn btn-default"})
</div>

@section Scripts {
   <script>
       function prideti(sk) {

        document.getElementById('header').style.visibility = "visible";
        var tmp_row = `"<tr>
                     <td style="padding-top:10px"">
                        <input class="form-control text-box single-line" data-val="true" data-val-required="Vardo laukas yra būtinas" id="darbuotojas`+ sk + `__Vardas" name="Darbuotojai[` + sk + `].Vardas" type="text" value="">
                        @Html.ValidationMessageFor(Model => Model.Darbuotojai[0].Vardas, "", new { @class = "text-danger" })
                    </td>
                     <td style="padding-left:10px; padding-top:10px">
                        <input class="form-control text-box single-line" data-val="true" data-val-required="Pavardės laukas yra būtinas" id="darbuotojas`+ sk + `__Pavarde" name="Darbuotojai[` + sk + `].Pavarde" type="text" value="">
                        @Html.ValidationMessageFor(Model => Model.Darbuotojai[0].Pavarde, "", new { @class = "text-danger" })
                     </td>
                     <td style="padding-left:10px; padding-top:10px">
                        <input class="form-control text-box single-line" data-val="true" data-val-required="Einamų pareigų laukas yra būtinas" id="darbuotojas`+ sk + `__EinamosPareigos" name="Darbuotojai[` + sk + `].EinamosPareigos" type="text" value="">
                        @Html.ValidationMessageFor(Model => Model.Darbuotojai[0].EinamosPareigos, "", new { @class = "text-danger" })
                     </td>
                        <td style="padding-left:10px; padding-top:10px"><button type="button" class="btn btn-danger" onclick="salinti(this)">Šalinti</button></td>
                    </tr>"`;

        $("#darbuotojai_tbl tr:last").after(tmp_row);

        $('#hCount').val(Number($('#hCount').val()) + 1);

    };

    function salinti(btn) {
        $(btn).closest('tr').remove();


        var cnt = 0;

        $("#darbuotojai_tbl tbody tr").each(function () {
            var tmp_row = "<tr>" + $(this).html() + "</tr>";
            var new_tmp_row = tmp_row.replace(/\[(.)\]/g, "[" + cnt + "]");
            new_tmp_row = new_tmp_row.replace(/\_(.)\_/g, "_" + cnt + "_");
            $(this).replaceWith(new_tmp_row);
            cnt = cnt + 1;
        });

        $('#hCount').val(cnt);

    }
</script>
}

2 Laboras/Views/Krepsinio_komanda/Delete.cshtml
@model _2_Laboras.ViewModels.KrepsinioKomandaEditViewModel

@{
    ViewBag.Title = "Komandos šalinimas";
}

<h2>Komandos šalinimas</h2>

<h3>Ar tikrai norite pašalinti šią komandą?</h3>
<div>
    <h4>Krepšinio komanda</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.KrepsinioKomanda.Pavadinimas)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.KrepsinioKomanda.Pavadinimas)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.KrepsinioKomanda.Miestas)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.KrepsinioKomanda.Miestas)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.KrepsinioKomanda.Treneris)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.KrepsinioKomanda.Treneris)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.KrepsinioKomanda.Biudzetas)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.KrepsinioKomanda.Biudzetas)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.KrepsinioKomanda.Arena)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.KrepsinioKomanda.Arena)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.KrepsinioKomanda.Lygu_licenzija)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.KrepsinioKomanda.Lygu_licenzija)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.KrepsinioKomanda.Laimejimai)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.KrepsinioKomanda.Laimejimai)
        </dd>

    </dl>
</div>
    <div>

          <h4>Darbuotojai</h4>
        <hr />
        <table class="table table-striped">
            <tr style="background-color:lightblue">
                <th>
                    @Html.DisplayNameFor(model => model.Darbuotojai[0].Vardas)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Darbuotojai[0].Pavarde)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Darbuotojai[0].EinamosPareigos)
                </th>
            </tr>

              @for (int i = 0; i < Model.Darbuotojai.Count; i++)
            {
                <tr>
                    <td>@Model.Darbuotojai[i].Vardas</td>
                    <td>@Model.Darbuotojai[i].Pavarde</td>
                    <td>@Model.Darbuotojai[i].EinamosPareigos</td>
                </tr>
            }

        </table> 

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()
            <div class="form-actions no-color">
                <h2>@ViewBag.klaida</h2>
                <input type="submit" value="Šalinti" class="btn btn-danger" />
                @Html.ActionLink("Atgal į sąrašą", "Index", "Krepsinio_komanda", new { @class = "btn btn-default" })
            </div>
        }
    </div>

2 Laboras/Views/Krepsinio_komanda/Edit.cshtml
@model _2_Laboras.ViewModels.KrepsinioKomandaEditViewModel

@{ var psl_k_count = 0; }
@{
    ViewBag.Title = "Komandos redagavimas";
}


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="form-horizontal">
        <h4>Komandos redagavimas</h4>
        <hr />
        <fieldset>
            <legend>Komandos informacija</legend>
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.KrepsinioKomanda.Pavadinimas, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.KrepsinioKomanda.Pavadinimas, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.KrepsinioKomanda.Pavadinimas, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.KrepsinioKomanda.Miestas, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.KrepsinioKomanda.Miestas, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.KrepsinioKomanda.Miestas, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.KrepsinioKomanda.Treneris, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.KrepsinioKomanda.Treneris, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.KrepsinioKomanda.Treneris, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.KrepsinioKomanda.Biudzetas, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.KrepsinioKomanda.Biudzetas, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.KrepsinioKomanda.Biudzetas, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.KrepsinioKomanda.Arena, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.KrepsinioKomanda.Arena, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.KrepsinioKomanda.Arena, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.KrepsinioKomanda.Lygu_licenzija, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.KrepsinioKomanda.Lygu_licenzija, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.KrepsinioKomanda.Lygu_licenzija, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.KrepsinioKomanda.Laimejimai, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.KrepsinioKomanda.Laimejimai, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.KrepsinioKomanda.Laimejimai, "", new { @class = "text-danger" })
                </div>
            </div>
            @{if (Model.Darbuotojai != null)
                {
                    psl_k_count = Model.Darbuotojai.Count;
                }
                else
                {
                    psl_k_count = 0;
                }
            }
        </fieldset>

        <fieldset>
            <legend>Darbuotojų informacija</legend>
            <table class="table-responsive" id="darbuotojai_tbl">
                <thead>
                    <tr>
                        <th>Vardas</th>
                        <th>Pavardė</th>
                        <th>Einamos pareigos</th>
                    </tr>
                </thead>
                @if (Model.Darbuotojai != null)
                {
                    for (int i = 0; i < Model.Darbuotojai.Count; i++)
                    {
                        <tr>
                            <td style="padding-top:10px">
                                @Html.EditorFor(model => model.Darbuotojai[i].Vardas, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(Model => Model.Darbuotojai[i].Vardas, "", new { @class = "text-danger" })
                            </td>
                            <td style="padding-left:10px; padding-top:10px">
                                @Html.EditorFor(model => model.Darbuotojai[i].Pavarde, new { htmlAttributes = new { @class = "form-control date-picker" } })
                                @Html.ValidationMessageFor(Model => Model.Darbuotojai[i].Pavarde, "", new { @class = "text-danger" })
                            </td>
                            <td style="padding-left:10px; padding-top:10px">
                                @Html.EditorFor(model => model.Darbuotojai[i].EinamosPareigos, new { htmlAttributes = new { @class = "form-control date-picker" } })
                                @Html.ValidationMessageFor(Model => Model.Darbuotojai[i].EinamosPareigos, "", new { @class = "text-danger" })
                            </td>
                            <td style="padding-left:10px; padding-top:10px"><button type="button" class="btn btn-danger" onclick="salinti(this)">Šalinti</button></td>
                        </tr>
                    }
                }
            </table>
            <input type="hidden" disabled value="@psl_k_count" id="hCount" />
            <button id="prd" type="button" class="btn btn-info" onclick="prideti($('#hCount').val());" style="margin-top: 10px">Pridėti</button>
                <input type="submit" value="Išsaugoti" class="btn btn-success" style="margin-top: 10px" />
            
        </fieldset>

    </div>

}

<div>
    @Html.ActionLink("Atgal į sąrašą »", "Index", "Krepsinio_komanda", new { @class = "btn btn-default" })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script>
        function prideti(sk) {

            var tmp_row = `"<tr>
                             <td style="padding-top:10px">
                                <input class="form-control text-box single-line" data-val-required="Vardo laukas yra būtinas" id="darbuotojas`+ sk + `__Vardas" name="Darbuotojai[` + sk + `].Vardas" type="text" value="">
                            </td>
                             <td style="padding-left:10px; padding-top:10px">
                                <input class="form-control text-box single-line" data-val-required="Pavardės laukas yra būtinas" id="darbuotojas`+ sk + `__Pavarde" name="Darbuotojai[` + sk + `].Pavarde" type="text" value="">
                             </td>
                             <td style="padding-left:10px; padding-top:10px">
                                <input class="form-control text-box single-line" data-val-required="Einamų pareigų laukas yra būtinas" id="darbuotojas`+ sk + `__EinamosPareigos" name="Darbuotojai[` + sk + `].EinamosPareigos" type="text" value="">
                             </td>
                                <td style="padding-left:10px; padding-top:10px"><button type="button" class="btn btn-danger" onclick="salinti(this)">Šalinti</button></td>
                            </tr>"`;

            $("#darbuotojai_tbl tr:last").after(tmp_row);

            $('#hCount').val(Number($('#hCount').val()) + 1);

        };

        function salinti(btn) {
            $(btn).closest('tr').remove();


            var cnt = 0;

            $("#darbuotojai_tbl tbody tr").each(function () {
                var tmp_row = "<tr>" + $(this).html() + "</tr>";
                var new_tmp_row = tmp_row.replace(/\[(.)\]/g, "[" + cnt + "]");
                new_tmp_row = new_tmp_row.replace(/\_(.)\_/g, "_" + cnt + "_");
                $(this).replaceWith(new_tmp_row);
                cnt = cnt + 1;
            });

            $('#hCount').val(cnt);

        }
    </script>
}

2 Laboras/Views/Krepsinio_komanda/Index.cshtml
@model IEnumerable<_2_Laboras.Models.Krepsinio_komanda>

@{
    ViewBag.Title = "Krepšinio komandos";
}

<h2>Krepšinio komandos</h2>

<p>
    @Html.ActionLink("Nauja komanda", "Create", "Krepsinio_komanda", new { @class="btn btn-success"})
</p>
<table class="table">
    <thead>
        <tr style="background-color: lightblue; ">
            <th>
                @Html.DisplayNameFor(model => model.Pavadinimas)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Miestas)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Treneris)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Biudzetas)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Arena)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Lygu_licenzija)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Laimejimai)
            </th>
            <th style="width: 18%"></th>
        </tr>
    </thead>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Pavadinimas)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Miestas)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Treneris)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Biudzetas)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Arena)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Lygu_licenzija)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Laimejimai)
                </td>
                <td>
                    @Html.ActionLink("Redaguoti", "Edit", new { id = item.id }, new { @class = "btn btn-primary action" })
                    @Html.ActionLink("Šalinti", "Delete", new { id = item.id }, new { @class = "btn btn-danger action" })
                </td>
            </tr>
        }

</table>