2 Laboras/Models/Krepsinio_lyga.cs
using System;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;


namespace _2_Laboras.Models
{
    public class Krepsinio_lyga
    {
        [DisplayName("Lygos pavadinimas")]
        [Required]
        public string Lygos_pavadinimas { get; set; }

        [DisplayName("Prizinis fondas")]
        [Required]
        public int Prizinis_fondas { get; set; }

        [DisplayName("Komandų skaičius")]
        [Required]
        public int Komandu_skaicius { get; set; }

        [DisplayName("Turnyro trukmė")]
        [Required]
        public string Turnyro_trukme { get; set; }

        [DisplayName("Formatas")]
        [Required]
        public string Formatas { get; set; }

        public string Remejas { get; set; }

        [DisplayName("ID")]
        [Required]
        public int id { get; set; }
    }
}

2 Laboras/Controllers/Krepsinio_lygaController.cs
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Web.Mvc;
using _2_Laboras.Models;
using _2_Laboras.Repos;
using _2_Laboras.ViewModels;

namespace _2_Laboras.Controllers
{
    public class Krepsinio_lygaController : Controller
    {
        Krepsinio_LygaRepository krepsinio_LygaRepository = new Krepsinio_LygaRepository();
        ImoneRepository ImoneRepository = new ImoneRepository();
        PrezidentasRepository prezidentasRepository = new PrezidentasRepository();
        public ActionResult Index()
        {
            return View(krepsinio_LygaRepository.getLyga());
        }

        public ActionResult Create()
        {
            KrepsinioLygaEditViewModel krepsinioLyga = new KrepsinioLygaEditViewModel();
            PopulateSelections(krepsinioLyga);
            return View(krepsinioLyga);
        }

        [HttpPost]
        public ActionResult Create(KrepsinioLygaEditViewModel krepsinio_Lyga)
        {
            try
            {
                bool exist = krepsinio_LygaRepository.findDublicates(krepsinio_Lyga.LygosPavadinimas);
                if (exist)
                {
                    ViewBag.klaida = "Komanda su tokiu pavadinimu jau egzistuoja";
                    PopulateSelections(krepsinio_Lyga);
                    return View(krepsinio_Lyga);
                }

                if (ModelState.IsValid)
                {
                    krepsinio_LygaRepository.addLyga(krepsinio_Lyga);
                    if (krepsinio_Lyga.PrezidentoKadencijos != null)
                    {
                        int lygosID = krepsinio_LygaRepository.getIDbyName(krepsinio_Lyga.LygosPavadinimas);
                        
                        foreach (var kadencijosInfo in krepsinio_Lyga.PrezidentoKadencijos)
                        {
                            if (kadencijosInfo.KadencijosPradzia < kadencijosInfo.KadencijosPabaiga)
                            {
                                prezidentasRepository.addPrezidentoKadencija(lygosID, kadencijosInfo);
                            }

                            else
                            {
                                ViewBag.klaida = "Kadencijos pabaiga turi būti vėliau nei pradžia";
                                PopulateSelections(krepsinio_Lyga);
                                return View(krepsinio_Lyga);
                            }
                        }
                    }
                }

                return RedirectToAction("Index");
            }
            catch
            {
                PopulateSelections(krepsinio_Lyga);
                return View(krepsinio_Lyga);
            }
        }

        public ActionResult Edit(int id)
        {
            KrepsinioLygaEditViewModel krepsinioLygaEditViewModel = new KrepsinioLygaEditViewModel();
            krepsinioLygaEditViewModel = krepsinio_LygaRepository.getLyga(id);
            krepsinioLygaEditViewModel.PrezidentoKadencijos = prezidentasRepository.getKadencijos(id);
            PopulateSelections(krepsinioLygaEditViewModel);
            return View(krepsinioLygaEditViewModel);
        }

        [HttpPost]
        public ActionResult Edit(int id,KrepsinioLygaEditViewModel krepsinio_Lyga)
        {
            try
            {
                bool exist = krepsinio_LygaRepository.findDbulicatesForEdit(krepsinio_Lyga.LygosPavadinimas, id);
                if (exist)
                {
                    ViewBag.klaida = "Komanda su tokiu pavadinimu jau egzistuoja";
                    PopulateSelections(krepsinio_Lyga);
                    return View(krepsinio_Lyga);
                }


                krepsinio_LygaRepository.updateLyga(id,krepsinio_Lyga);
                
                if(krepsinio_Lyga.PrezidentoKadencijos != null)
                {
                    prezidentasRepository.deleteKadencija(id);
                    foreach (var prezidentas in krepsinio_Lyga.PrezidentoKadencijos)
                    {
                        if (prezidentas.KadencijosPradzia < prezidentas.KadencijosPabaiga)
                        {
                            prezidentas.fk_komanda = id;
                            prezidentasRepository.addPrezidentoKadencija(id,prezidentas);
                        }

                        else
                        {
                            ViewBag.klaida = "Kadencijos pabaiga turi būti vėliau nei pradžia";
                            PopulateSelections(krepsinio_Lyga);
                            return View(krepsinio_Lyga);
                        }
                    }
                }
              
                return RedirectToAction("Index");
            }
            catch
            {
                PopulateSelections(krepsinio_Lyga);
                return View(krepsinio_Lyga);
            }
        }

        public ActionResult Delete(int id)
        {
            KrepsinioLygaEditViewModel krepsinioLygaEditViewModel = new KrepsinioLygaEditViewModel();
            krepsinioLygaEditViewModel = krepsinio_LygaRepository.getLyga(id);
            krepsinioLygaEditViewModel.PrezidentoKadencijos = prezidentasRepository.getKadencijos(id);
            return View(krepsinioLygaEditViewModel);
        }

        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                KrepsinioLygaEditViewModel krepsinioLygaEditViewModel = new KrepsinioLygaEditViewModel();
                krepsinioLygaEditViewModel = krepsinio_LygaRepository.getLyga(id);
                krepsinioLygaEditViewModel.PrezidentoKadencijos = prezidentasRepository.getKadencijos(id);
                prezidentasRepository.deleteKadencija(id);
                krepsinio_LygaRepository.deleteLyga(id);
                return RedirectToAction("Index");
            }

            catch
            {
                return View();
            }
        }

        public void PopulateSelections(KrepsinioLygaEditViewModel krepsinioLyga)
        {
            var imones = ImoneRepository.getImones();
            var prezidentai = prezidentasRepository.getPrezidentai();
            List<SelectListItem> selectListImones = new List<SelectListItem>();
            List<SelectListItem> selectListPrezidentai = new List<SelectListItem>();

            foreach (var imone in imones)
            {
                selectListImones.Add(new SelectListItem() { Value = Convert.ToString(imone.id), Text = imone.Pavadinimas + " - " + imone.GaminamaProdukcija});
            }

            krepsinioLyga.RemejaiList = selectListImones;
          
            foreach (var prezidentas in prezidentai)
            {
                selectListPrezidentai.Add(new SelectListItem() { Value = Convert.ToString(prezidentas.id), Text = prezidentas.Vardas + " " + prezidentas.Pavarde});
            }

            krepsinioLyga.PrezidentaiList = selectListPrezidentai;
        }
    }
}

2 Laboras/Views/Krepsinio_lyga/Create.cshtml
@model _2_Laboras.ViewModels.KrepsinioLygaEditViewModel

@{
    ViewBag.Title = "Nauja krepšinio lyga";
}

<h2>Nauja krepšinio lyga</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Krepšinio lyga</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <fieldset>
        <legend>Krepšinio lygos informacijs</legend>
        <div class="form-group">
            @Html.LabelFor(model => model.LygosPavadinimas, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LygosPavadinimas, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LygosPavadinimas, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PrizinisFondas, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PrizinisFondas, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PrizinisFondas, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.KomanduSkaicius, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.KomanduSkaicius, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.KomanduSkaicius, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TurnyroTrukme, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TurnyroTrukme, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TurnyroTrukme, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Formatas, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Formatas, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Formatas, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.fk_remejas, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.fk_remejas, Model.RemejaiList, "--------------", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.fk_remejas, "", new { @class = "text-danger" })
            </div>
        </div>

    </fieldset>

    <fieldset>
        <legend>Krepšinio lygos prezidentų kadencijos</legend>
        <table class="table table-responsive" id="prezidentai_tbl">
            <thead id="header" style="visibility: hidden">
                <tr>
                    <th>Prezidentas</th>
                    <th>Kadencijos pradžia</th>
                    <th>Kadencijos pabaiga</th>
                </tr>
            </thead>
        </table>
        <input type="hidden" disabled value=0 id="hCount" />
        <button id="prd" type="button" class="btn btn-info" onclick="prideti($('#hCount').val());" style="margin-top: 10px">Pridėti</button>
        @if (ViewBag.klaida != null)
        {
            <h5 style="color:red">@ViewBag.klaida</h5>
        }
        else
        {
            <input type="submit" value="Išsaugoti" class="btn btn-success" style="margin-top: 10px" />
        }
    </fieldset>

    </div>
}

<div>
    @Html.ActionLink("Atgal į sąrašą »", "Index", "Krepsinio_lyga", new { @class = "btn btn-default" })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script>
        function prideti(sk) {
            document.getElementById('header').style.visibility = "visible";
            var tmp_row = `"<tr>
                            <td>
                           <span class="text-hide sel_element"></span>
                             @Html.DropDownList("PrezidentoKadencijos[0].fk_prezidentas", Model.PrezidentaiList, "--------------", new { @class = "form-control" })
                            </td>
                         <td style="padding-top:10px">
                            <input class="form-control text-box single-line valid date-picker" data-val="true" data-val-date="The field galiojaIki must be a date."  data-val-required="The galiojaIki field is required." id="PrezidentoKadencijos_0__KadencijosPradzia" name="PrezidentoKadencijos[0].KadencijosPradzia" type="datetime" value="">
                         </td>
                         <td style="padding-top:10px">
                             <input class="form-control text-box single-line valid date-picker" data-val="true" data-val-date="The field galiojaIki must be a date."  data-val-required="The galiojaIki field is required." id="PrezidentoKadencijos_0__KadencijosPabaiga" name="PrezidentoKadencijos[0].KadencijosPabaiga" type="datetime" value="">
                         </td>
                            <td><button type="button" class="btn btn-danger" onclick="salinti(this)">Šalinti</button></td>
                        </tr>"`;

         var new_tmp_row = tmp_row.replace(/\[(0)\]/g, "[" + sk + "]");
        new_tmp_row = new_tmp_row.replace(/\_(0)\_/g, "_" + sk + "_");
            $("#prezidentai_tbl tr:last").after(new_tmp_row);

            $('#hCount').val(Number($('#hCount').val()) + 1);
            $(".date-picker").datepicker({ dateFormat: 'yy-mm-dd' });

        };

        function salinti(btn) {
            $(btn).closest('tr').remove();


            var cnt = 0;

            $("#prezidentai_tbl tbody tr").each(function () {
                var tmp_row = "<tr>" + $(this).html() + "</tr>";
                var new_tmp_row = tmp_row.replace(/\[(.)\]/g, "[" + cnt + "]");
                new_tmp_row = new_tmp_row.replace(/\_(.)\_/g, "_" + cnt + "_");
                $(this).replaceWith(new_tmp_row);
                cnt = cnt + 1;
            });

            $('#hCount').val(cnt);
           $(".sel_element").each(function () {
            $(this).closest("td").find("select").val($(this).text());
        });
        }
    </script>
}

2 Laboras/Views/Krepsinio_lyga/Delete.cshtml
@model _2_Laboras.ViewModels.KrepsinioLygaEditViewModel

@{
    ViewBag.Title = "Krepšinio lygos šalinimas";
}

    <h2>Krepšinio lygos šalinimas</h2>

<h3>Ar tikrai norite pašalinti šią krepšinio lygą?</h3>
<div>
    <h4>Krepšinio lyga</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.LygosPavadinimas)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.LygosPavadinimas)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.PrizinisFondas)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.PrizinisFondas)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.KomanduSkaicius)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.KomanduSkaicius)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.TurnyroTrukme)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.TurnyroTrukme)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Remejas)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Remejas)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Formatas)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Formatas)
        </dd>

    </dl>
</div>
<div>

    <h4>Darbuotojai</h4>
    <hr />
    <table class="table table-striped">
        <tr style="background-color:lightblue">
            <th>
                @Html.DisplayNameFor(model => model.PrezidentoKadencijos[0].vardas)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PrezidentoKadencijos[0].pavarde)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PrezidentoKadencijos[0].KadencijosPradzia)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PrezidentoKadencijos[0].KadencijosPabaiga)
            </th>
        </tr>

        @for (int i = 0; i < Model.PrezidentoKadencijos.Count; i++)
        {
        <tr>
            <td>@Model.PrezidentoKadencijos[i].vardas</td>
            <td>@Model.PrezidentoKadencijos[i].pavarde</td>
            <td>@Model.PrezidentoKadencijos[i].KadencijosPabaiga</td>
            <td>@Model.PrezidentoKadencijos[i].KadencijosPabaiga</td>
        </tr>
        }

    </table>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        <div class="form-actions no-color">
            <h2>@ViewBag.klaida</h2>
            <input type="submit" value="Šalinti" class="btn btn-danger" />
            @Html.ActionLink("Atgal į sąrašą", "Index", "Krepsinio_lyga", new { @class = "btn btn-default" })
        </div>
    }
</div>

2 Laboras/Views/Krepsinio_lyga/Edit.cshtml
@model _2_Laboras.ViewModels.KrepsinioLygaEditViewModel

@{
    ViewBag.Title = "Krepšinio lygos redagavimas";
    var psl_k_count = 0;
}

<h2>Krepšinio lygos redagavimas</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
<div class="form-horizontal">
    <h4>Krepšinio lygosredagavimas</h4>
    <hr />
    <fieldset>
        <legend>Krepšinio lygos informacija</legend>
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.LygosPavadinimas, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LygosPavadinimas, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LygosPavadinimas, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PrizinisFondas, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PrizinisFondas, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PrizinisFondas, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.KomanduSkaicius, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.KomanduSkaicius, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.KomanduSkaicius, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TurnyroTrukme, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TurnyroTrukme, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TurnyroTrukme, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Formatas, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Formatas, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Formatas, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.fk_remejas, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.fk_remejas, Model.RemejaiList, "--------------", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.fk_remejas, "", new { @class = "text-danger" })
            </div>
    </fieldset>

    @{if (Model.PrezidentoKadencijos != null)
        {
            psl_k_count = Model.PrezidentoKadencijos.Count;
        }
        else
        {
            psl_k_count = 0;
        }
    }
    <fieldset>
        <legend>Prezidentų kadencijos informacija</legend>
        <table class="table-responsive" id="prezidentai_tbl">
            <thead>
                <tr>
                    <th>Prezidentas </th>
                    <th>Kadencijos pradžia </th>
                    <th>Kadencijos pabaigas</th>
                </tr>
            </thead>
                @for (int i = 0; i < Model.PrezidentoKadencijos.Count; i++)
        {
                    <tr>
                        <td style="padding-top:10px">
                            <span class="text-hide sel_element" style="display: none;">@Model.PrezidentoKadencijos[i].fk_prezidentas</span>
                            @Html.DropDownListFor(model => model.PrezidentoKadencijos[i].fk_prezidentas, Model.PrezidentaiList, "--------------", new { @class = "form-control" })
                        </td>
                        <td style="padding-left:10px; padding-top:10px">
                            @Html.EditorFor(model => model.PrezidentoKadencijos[i].KadencijosPradzia, new { htmlAttributes = new { @class = "form-control date-picker" } })
                        </td>
                        <td style="padding-left:10px; padding-top:10px">
                            @Html.EditorFor(model => model.PrezidentoKadencijos[i].KadencijosPabaiga, new { htmlAttributes = new { @class = "form-control date-picker" } })
                        </td>
                        <td style="padding-left:10px; padding-top:10px"><button type="button" class="btn btn-danger" onclick="salinti(this)">Šalinti</button></td>
                    </tr>
            }
        


        </table>
        <input type="hidden" disabled value="@psl_k_count" id="hCount" />
        <button id="prd" type="button" class="btn btn-info" onclick="prideti($('#hCount').val());" style="margin-top: 10px">Pridėti</button>
        @if (ViewBag.klaida != null)
        {
            <h5 style="color:red">@ViewBag.klaida</h5>
        }
        else
        {
            <input type="submit" value="Išsaugoti" class="btn btn-success" style="margin-top: 10px" />
        }
       
    </fieldset>
</div>
}

<div>
    @Html.ActionLink("Atgal į sąrašą »", "Index", "Krepsinio_lyga", new { @class = "btn btn-default" })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script>
        function prideti(sk) {

            var tmp_row = `"<tr>
                            <td style="padding-top:10px">
                           <span class="text-hide sel_element"></span>
                             @Html.DropDownList("PrezidentoKadencijos[0].fk_prezidentas", Model.PrezidentaiList, "--------------", new { @class = "form-control" })
                            </td>
                         <td style="padding-left:10px; padding-top:10px"">
                            <input class="form-control text-box single-line valid date-picker" data-val="true" data-val-date="The field galiojaIki must be a date."  data-val-required="The galiojaIki field is required." id="PrezidentoKadencijos_0__KadencijosPradzia" name="PrezidentoKadencijos[0].KadencijosPradzia" type="datetime" value="">
                         </td>
                         <td style="padding-left:10px; padding-top:10px">
                             <input class="form-control text-box single-line valid date-picker" data-val="true" data-val-date="The field galiojaIki must be a date."  data-val-required="The galiojaIki field is required." id="PrezidentoKadencijos_0__KadencijosPabaiga" name="PrezidentoKadencijos[0].KadencijosPabaiga" type="datetime" value="">
                         </td>
                            <td style="padding-left:10px; padding-top:10px"><button type="button" class="btn btn-danger" onclick="salinti(this)">Šalinti</button></td>
                        </tr>"`;

         var new_tmp_row = tmp_row.replace(/\[(0)\]/g, "[" + sk + "]");
        new_tmp_row = new_tmp_row.replace(/\_(0)\_/g, "_" + sk + "_");
            $("#prezidentai_tbl tr:last").after(new_tmp_row);

            $('#hCount').val(Number($('#hCount').val()) + 1);
            $(".date-picker").datepicker({ dateFormat: 'yy-mm-dd' });

        };

        function salinti(btn) {
            $(btn).closest('tr').remove();

            var cnt = 0;

            $("#prezidentai_tbl tbody tr").each(function () {
                var tmp_row = "<tr>" + $(this).html() + "</tr>";
                var new_tmp_row = tmp_row.replace(/\[(.)\]/g, "[" + cnt + "]");
                new_tmp_row = new_tmp_row.replace(/\_(.)\_/g, "_" + cnt + "_");
                $(this).replaceWith(new_tmp_row);
                cnt = cnt + 1;
            });

            $('#hCount').val(cnt);
           $(".sel_element").each(function () {
            $(this).closest("td").find("select").val($(this).text());
        });
        }
    </script>

}

2 Laboras/Views/Krepsinio_lyga/Index.cshtml
@model IEnumerable<_2_Laboras.Models.Krepsinio_lyga>

@{
    ViewBag.Title = "Krepšinio lygos";
}

<h2>Krepšinio lygos</h2>

<p>
    @Html.ActionLink("Nauja krepšinio lyga", "Create", "Krepsinio_lyga", new { @class="btn btn-success"})
</p>
<table class="table">
    <thead>
        <tr style="background-color: lightblue; ">
            <th>
                @Html.DisplayNameFor(model => model.Lygos_pavadinimas)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Prizinis_fondas)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Komandu_skaicius)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Turnyro_trukme)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Formatas)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Remejas)
            </th>
            <th style="width: 18%"></th>
        </tr>
    </thead>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Lygos_pavadinimas)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Prizinis_fondas)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Komandu_skaicius)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Turnyro_trukme)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Formatas)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Remejas)
            </td>
            <td>
                @Html.ActionLink("Redaguoti", "Edit", new { id = item.id }, new { @class = "btn btn-primary action" }) 
                @Html.ActionLink("Šalinti", "Delete", new { id = item.id }, new { @class = "btn btn-danger action" })
            </td>
        </tr>
    }

</table>